// <copyright file="ITypedAccessor.cs" company="Allors bvba">
// Copyright (c) Allors bvba. All rights reserved.
// Licensed under the LGPL license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Allors.Documents.Expressions;

/// <summary>
/// Resolves members of a model type without reflection.
/// Implementations are usually generated by the Allors.Documents source generator.
/// </summary>
public interface ITypedAccessor
{
    /// <summary>Tries to get the value of a member on the given instance.</summary>
    /// <param name="instance">The instance to read from.</param>
    /// <param name="member">The member name.</param>
    /// <param name="value">The member value when found.</param>
    /// <returns><see langword="true"/> when the member exists.</returns>
    bool TryGet(object instance, string member, out object? value);
}
